name: CI workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Generate Amplify outputs
        run: npx ampx generate outputs --branch main --app-id d2ls60adq9c2xf

      - name: Run Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - run: echo "Running empty CI workflow for pull request to main branch"
